language: objective-c
env:
global:
   - MODULE_NAME=ti.barcode
before_install:
    - MODULE_ROOT=/Users/mdadu/documents/Git/ti.barcode
install:
    - cd 
    - curl -o install.sh https://raw.githubusercontent.com/appcelerator-modules/ci/master/travis/install.sh
    - source install.sh -s 3.2.2.GA
script: 
    - curl -o script.sh https://raw.githubusercontent.com/appcelerator-modules/ci/master/travis/script.sh
    - source script.sh
after_success: # and this only on success
    - curl -o deploy.sh https://raw.githubusercontent.com/appcelerator-modules/ci/master/travis/deploy.sh
    - source deploy.sh
